FROM gcr.io/google-appengine/php72

ENV DOCUMENT_ROOT /app/public
ENV SKIP_LOCKDOWN_DOCUMENT_ROOT true

# Allow customizing some composer flags
ARG COMPOSER_FLAGS='--no-scripts --no-dev --prefer-dist'
ENV COMPOSER_FLAGS=${COMPOSER_FLAGS}

# SUPERVISORD additional config
COPY additional-supervisord.conf /etc/supervisor/conf.d/additional-supervisord.conf

# CUSTOM ENTRYPOINT (will also trigger the default Google entrypoint)
RUN mkdir /additional-build-scripts
COPY entrypoint.sh /additional-build-scripts/entrypoint.sh
RUN chown -R www-data /additional-build-scripts

ENTRYPOINT ["/additional-build-scripts/entrypoint.sh"]

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

